// Code generated by "stringer -type Register registers.go"; DO NOT EDIT.

package registers

import "strconv"

const _Register_name = "IDCONFIG1CONFIG2CONFIG3LOFFCH1SETCH2SETCH3SETCH4SETCH5SETCH6SETCH7SETCH8SETBIAS_SENSPBIAS_SENSNLOFF_SENSPLOFF_SENSNLOFF_FLIPLOFF_STATPLOFF_STATNGPIOMISC1MISC2CONFIG4"

var _Register_index = [...]uint8{0, 2, 9, 16, 23, 27, 33, 39, 45, 51, 57, 63, 69, 75, 85, 95, 105, 115, 124, 134, 144, 148, 153, 158, 165}

func (i Register) String() string {
	if i >= Register(len(_Register_index)-1) {
		return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Register_name[_Register_index[i]:_Register_index[i+1]]
}
