// Code generated by "stringer -type SpiCmd spicmd.go"; DO NOT EDIT.

package ads1299

import "strconv"

const (
	_SpiCmd_name_0 = "WAKEUP"
	_SpiCmd_name_1 = "STANDBY"
	_SpiCmd_name_2 = "RESET"
	_SpiCmd_name_3 = "START"
	_SpiCmd_name_4 = "STOP"
	_SpiCmd_name_5 = "RDATACSDATAC"
	_SpiCmd_name_6 = "RREG"
	_SpiCmd_name_7 = "WREG"
)

var (
	_SpiCmd_index_5 = [...]uint8{0, 6, 12}
)

func (i SpiCmd) String() string {
	switch {
	case i == 2:
		return _SpiCmd_name_0
	case i == 4:
		return _SpiCmd_name_1
	case i == 6:
		return _SpiCmd_name_2
	case i == 8:
		return _SpiCmd_name_3
	case i == 10:
		return _SpiCmd_name_4
	case 16 <= i && i <= 17:
		i -= 16
		return _SpiCmd_name_5[_SpiCmd_index_5[i]:_SpiCmd_index_5[i+1]]
	case i == 32:
		return _SpiCmd_name_6
	case i == 64:
		return _SpiCmd_name_7
	default:
		return "SpiCmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
